seg 23 dez 2024 21:44:49 -04 Vilmar Catafesta <vcatafesta@gmail.com>

diff --git a/.github/workflows/build-package.yml b/.github/workflows/build-package.yml
--- a/.github/workflows/build-package.yml
+++ b/.github/workflows/build-package.yml
@@ -141,6 +141,14 @@ jobs:
           alias ls='ls -lha --color=auto'
           alias dir='ls -lha --color=auto'
 
+          die() {
+            local msg="$1"
+            msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+            echo -e "BIV=>${cyan}error: ${red}${msg}${reset}"
+            exit  1
+          }
+          export -f die
+
           msg_raw() {
             local msg="$1"
             # Remove tags HTML, se existirem
